-- MySQL Script generated by MySQL Workbench
-- lun 31 ago 2020 09:32:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bosco_bitacora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bosco_bitacora` ;

-- -----------------------------------------------------
-- Schema bosco_bitacora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bosco_bitacora` DEFAULT CHARACTER SET utf8 ;
USE `bosco_bitacora` ;

-- -----------------------------------------------------
-- Table `bosco_bitacora`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`user_type` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`user` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NULL,
  `names` VARCHAR(45) NULL,
  `last_names` VARCHAR(45) NULL,
  `lada` VARCHAR(4) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `rfc` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NULL,
  `country` ENUM('Perú', 'México', 'Chile', 'Bolivia') NULL,
  `location` ENUM('Perú', 'México', 'Chile', 'Bolivia') NULL,
  `id_user_type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type1_idx` (`id_user_type` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`id_user_type`)
    REFERENCES `bosco_bitacora`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`notes` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`layer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`layer` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`layer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`technology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`technology` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`technology` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `status` ENUM('active', 'inactive') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`subtechnology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`subtechnology` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`subtechnology` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`ticket` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(250) NULL,
  `status` ENUM('stand by', 'finished', 'cancel in process ', 'trashed', 'in process') NULL,
  `id_notes` INT NULL,
  `id_layer` INT NOT NULL,
  `id_owner` INT NULL,
  `id_technology` INT NOT NULL,
  `id_subtechnology` INT NULL,
  `priority` ENUM('relax', 'normal', 'now', 'right now', 'help me now') NULL,
  `difficulty` ENUM('easy', 'normal', 'hard', 'hardcore') NULL,
  `duration` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_notes1_idx` (`id_notes` ASC) VISIBLE,
  INDEX `fk_ticket_layer1_idx` (`id_layer` ASC) VISIBLE,
  INDEX `fk_ticket_user1_idx` (`id_owner` ASC) VISIBLE,
  INDEX `fk_ticket_language1_idx` (`id_technology` ASC) VISIBLE,
  INDEX `fk_ticket_sub_technology1_idx` (`id_subtechnology` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_notes1`
    FOREIGN KEY (`id_notes`)
    REFERENCES `bosco_bitacora`.`notes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_layer1`
    FOREIGN KEY (`id_layer`)
    REFERENCES `bosco_bitacora`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`id_owner`)
    REFERENCES `bosco_bitacora`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_language1`
    FOREIGN KEY (`id_technology`)
    REFERENCES `bosco_bitacora`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_sub_technology1`
    FOREIGN KEY (`id_subtechnology`)
    REFERENCES `bosco_bitacora`.`subtechnology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`team` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `slogan` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`user_has_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`user_has_team` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`user_has_team` (
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `team_id`),
  INDEX `fk_user_has_team_team1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_user_has_team_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_team_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bosco_bitacora`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_team_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `bosco_bitacora`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`project` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rfc` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `technology_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proyect_user1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_project_ticket1_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_project_technology1_idx` (`technology_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyect_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `bosco_bitacora`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `bosco_bitacora`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_technology1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `bosco_bitacora`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`team_has_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`team_has_project` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`team_has_project` (
  `id_team` INT NOT NULL,
  `id_project` INT NOT NULL,
  PRIMARY KEY (`id_team`, `id_project`),
  INDEX `fk_team_has_clients_clients1_idx` (`id_project` ASC) VISIBLE,
  INDEX `fk_team_has_clients_team1_idx` (`id_team` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_clients_team1`
    FOREIGN KEY (`id_team`)
    REFERENCES `bosco_bitacora`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_clients_clients1`
    FOREIGN KEY (`id_project`)
    REFERENCES `bosco_bitacora`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`rol` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`user_type_has_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`user_type_has_rol` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`user_type_has_rol` (
  `user_type_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`user_type_id`, `rol_id`),
  INDEX `fk_user_type_has_rol_rol1_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_user_type_has_rol_user_type1_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_type_has_rol_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `bosco_bitacora`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_has_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `bosco_bitacora`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bosco_bitacora`.`technology_has_subtechnology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bosco_bitacora`.`technology_has_subtechnology` ;

CREATE TABLE IF NOT EXISTS `bosco_bitacora`.`technology_has_subtechnology` (
  `technology_id` INT NOT NULL,
  `subtechnology_id` INT NOT NULL,
  PRIMARY KEY (`technology_id`, `subtechnology_id`),
  INDEX `fk_technology_has_subtechnology_subtechnology1_idx` (`subtechnology_id` ASC) VISIBLE,
  INDEX `fk_technology_has_subtechnology_technology1_idx` (`technology_id` ASC) VISIBLE,
  CONSTRAINT `fk_technology_has_subtechnology_technology1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `bosco_bitacora`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technology_has_subtechnology_subtechnology1`
    FOREIGN KEY (`subtechnology_id`)
    REFERENCES `bosco_bitacora`.`subtechnology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
