-- MySQL Script generated by MySQL Workbench
-- lun 27 jul 2020 12:38:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bitacora_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bitacora_db` ;

-- -----------------------------------------------------
-- Schema bitacora_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bitacora_db` ;
USE `bitacora_db` ;

-- -----------------------------------------------------
-- Table `bitacora_db`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`topic` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `title` VARCHAR(70) NOT NULL,
  `status` ENUM('active', 'inactive', 'suspended', 'deleted') NOT NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`programming_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`programming_language` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `title` VARCHAR(70) NOT NULL,
  `status` ENUM('active', 'inactive', 'suspended', 'deleted') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`topic_has_programming_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`topic_has_programming_language` (
  `topic_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `programming_language_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  PRIMARY KEY (`topic_id`, `programming_language_id`),
  INDEX `fk_topic_has_programming_language_programming_language1_idx` (`programming_language_id` ASC) VISIBLE,
  INDEX `fk_topic_has_programming_language_topic_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_has_programming_language_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `bitacora_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_has_programming_language_programming_language1`
    FOREIGN KEY (`programming_language_id`)
    REFERENCES `bitacora_db`.`programming_language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`framework_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`framework_library` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `name` VARCHAR(15) NOT NULL,
  `status` ENUM('active', 'inactive', 'suspended', 'deleted') NOT NULL,
  `isFramework` TINYINT NOT NULL,
  `version` VARCHAR(10) NULL,
  `versionDescription` VARCHAR(30) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`topic_has_framework_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`topic_has_framework_library` (
  `topic_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `framework_library_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  PRIMARY KEY (`topic_id`, `framework_library_id`),
  INDEX `fk_topic_has_framework_library_framework_library1_idx` (`framework_library_id` ASC) VISIBLE,
  INDEX `fk_topic_has_framework_library_topic1_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_has_framework_library_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `bitacora_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_has_framework_library_framework_library1`
    FOREIGN KEY (`framework_library_id`)
    REFERENCES `bitacora_db`.`framework_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`comment` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `title` VARCHAR(70) NOT NULL,
  `status` ENUM('active', 'inactive', 'suspended', 'deleted') NOT NULL,
  `content` VARCHAR(400) NOT NULL,
  `topic_id` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_topic1_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `bitacora_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`third_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`third_library` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `name` VARCHAR(15) NOT NULL,
  `status` ENUM('active', 'inactive', 'suspended', 'deleted') NOT NULL,
  `link` VARCHAR(400) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`topic_has_third_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`topic_has_third_library` (
  `topic_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `third_library_id` CHAR(36) NOT NULL DEFAULT (UUID()),
  PRIMARY KEY (`topic_id`, `third_library_id`),
  INDEX `fk_topic_has_third_library_third_library1_idx` (`third_library_id` ASC) VISIBLE,
  INDEX `fk_topic_has_third_library_topic1_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_has_third_library_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `bitacora_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_has_third_library_third_library1`
    FOREIGN KEY (`third_library_id`)
    REFERENCES `bitacora_db`.`third_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacora_db`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacora_db`.`files` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `url` VARCHAR(100) NOT NULL,
  `status` ENUM('active', 'inactive', 'suspended', 'deleted') NOT NULL,
  `type_file` VARCHAR(5) NOT NULL,
  `topic_id` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_topic1_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `bitacora_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
